name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    PORT: ${{secrets.PORT}}
    DB_URI: ${{secrets.DB_URI}}
    PROD_DB_URI: ${{secrets.PROD_DB_URI}}
    API_KEY: ${{secrets.API_KEY}}
    API_ENDPOINT: ${{secrets.API_ENDPOINT}}
    JWT_SECRET: ${{secrets.JWT_SECRET}}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test